
package com.epam.WebServices.AirTicketsService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AirTicketsService", targetNamespace = "http://localhost:1986/wss/AirTickets", wsdlLocation = "http://localhost:1986/wss/AirTickets?wsdl")
public class AirTicketsService
    extends Service
{

    private final static URL AIRTICKETSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.epam.WebServices.AirTicketsService.AirTicketsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.epam.WebServices.AirTicketsService.AirTicketsService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1986/wss/AirTickets?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1986/wss/AirTickets?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AIRTICKETSSERVICE_WSDL_LOCATION = url;
    }

    public AirTicketsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirTicketsService() {
        super(AIRTICKETSSERVICE_WSDL_LOCATION, new QName("http://localhost:1986/wss/AirTickets", "AirTicketsService"));
    }

    /**
     * 
     * @return
     *     returns AirTickets
     */
    @WebEndpoint(name = "AirTicketsPort")
    public AirTickets getAirTicketsPort() {
        return super.getPort(new QName("http://localhost:1986/wss/AirTickets", "AirTicketsPort"), AirTickets.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirTickets
     */
    @WebEndpoint(name = "AirTicketsPort")
    public AirTickets getAirTicketsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:1986/wss/AirTickets", "AirTicketsPort"), AirTickets.class, features);
    }

}
