
package com.epam.WebServices.AirTicketsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AirTickets", targetNamespace = "http://localhost:1986/wss/AirTickets")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AirTickets {


    /**
     * 
     * @param idTicket
     * @return
     *     returns boolean
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payForFlyTicket", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.PayForFlyTicket")
    @ResponseWrapper(localName = "payForFlyTicketResponse", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.PayForFlyTicketResponse")
    public boolean payForFlyTicket(
        @WebParam(name = "idTicket", targetNamespace = "")
        String idTicket)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws ParseException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookFlyTicket", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.BookFlyTicket")
    @ResponseWrapper(localName = "bookFlyTicketResponse", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.BookFlyTicketResponse")
    public int bookFlyTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Human arg1)
        throws IOException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param idTicket
     * @return
     *     returns boolean
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTicketById", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.DeleteTicketById")
    @ResponseWrapper(localName = "deleteTicketByIdResponse", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.DeleteTicketByIdResponse")
    public boolean deleteTicketById(
        @WebParam(name = "idTicket", targetNamespace = "")
        String idTicket)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.WebServices.AirTicketsService.FlyTicket
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketByNumber", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.GetTicketByNumber")
    @ResponseWrapper(localName = "getTicketByNumberResponse", targetNamespace = "http://localhost:1986/wss/AirTickets", className = "com.epam.WebServices.AirTicketsService.GetTicketByNumberResponse")
    public FlyTicket getTicketByNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ParseException_Exception
    ;

}
